-- URBANIZA - MIGRAÇÃO PARA FOTOS E VÍDEOS NAS AVALIAÇÕES
-- Execute este arquivo no SQL Editor do Supabase.

CREATE TABLE IF NOT EXISTS avaliacao_midias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id BIGINT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('foto', 'video')),
    url TEXT NOT NULL,
    caminho TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_midia_avaliacao
        FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_avaliacao_midias_avaliacao
    ON avaliacao_midias(avaliacao_id);

ALTER TABLE avaliacao_midias ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir leitura de midias" ON avaliacao_midias;
CREATE POLICY "Permitir leitura de midias"
ON avaliacao_midias FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Permitir envio de midias" ON avaliacao_midias;
CREATE POLICY "Permitir envio de midias"
ON avaliacao_midias FOR INSERT TO anon WITH CHECK (true);

-- Bucket público para que as mídias possam ser exibidas no site.
INSERT INTO storage.buckets (id, name, public)
VALUES ('avaliacoes', 'avaliacoes', true)
ON CONFLICT (id) DO UPDATE SET public = true;

DROP POLICY IF EXISTS "Permitir upload de midias das avaliacoes" ON storage.objects;
CREATE POLICY "Permitir upload de midias das avaliacoes"
ON storage.objects FOR INSERT TO anon
WITH CHECK (bucket_id = 'avaliacoes');

DROP POLICY IF EXISTS "Permitir leitura das midias das avaliacoes" ON storage.objects;
CREATE POLICY "Permitir leitura das midias das avaliacoes"
ON storage.objects FOR SELECT TO anon
USING (bucket_id = 'avaliacoes');
