CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE regioes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    descricao TEXT,
    area GEOMETRY(MULTIPOLYGON, 4326)
);

CREATE TABLE bairros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cidade TEXT NOT NULL DEFAULT 'Sorocaba',
    estado TEXT NOT NULL DEFAULT 'SP',
    regiao_id BIGINT NOT NULL,
    area GEOMETRY(MULTIPOLYGON, 4326),
    CONSTRAINT fk_bairro_regiao
        FOREIGN KEY (regiao_id) REFERENCES regioes(id)
        ON DELETE RESTRICT
);

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL UNIQUE,
    descricao TEXT
);

CREATE TABLE avaliacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bairro_id BIGINT NOT NULL,
    categoria_id BIGINT NOT NULL,
    nota INTEGER NOT NULL CHECK (nota BETWEEN 1 AND 10),
    comentario TEXT,
    localizacao GEOGRAPHY(POINT, 4326) NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_avaliacao_bairro
        FOREIGN KEY (bairro_id) REFERENCES bairros(id) ON DELETE RESTRICT,
    CONSTRAINT fk_avaliacao_categoria
        FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE RESTRICT
);

CREATE INDEX idx_bairros_regiao ON bairros(regiao_id);
CREATE INDEX idx_avaliacoes_bairro ON avaliacoes(bairro_id);
CREATE INDEX idx_avaliacoes_categoria ON avaliacoes(categoria_id);
CREATE INDEX idx_avaliacoes_localizacao ON avaliacoes USING GIST(localizacao);
CREATE INDEX idx_bairros_area ON bairros USING GIST(area);
CREATE INDEX idx_regioes_area ON regioes USING GIST(area);

INSERT INTO regioes (nome, descricao) VALUES
('Zona Norte', 'Região Norte de Sorocaba'),
('Zona Sul', 'Região Sul de Sorocaba'),
('Zona Leste', 'Região Leste de Sorocaba'),
('Zona Oeste', 'Região Oeste de Sorocaba');

INSERT INTO categorias (nome, descricao) VALUES
('Segurança', 'Avaliação da segurança da região'),
('Mobilidade', 'Avaliação do trânsito e deslocamento'),
('Iluminação Pública', 'Avaliação da iluminação das vias e espaços públicos'),
('Calçadas', 'Avaliação das condições das calçadas'),
('Asfalto e Vias', 'Avaliação das condições das ruas e pavimentação'),
('Limpeza Urbana', 'Avaliação da limpeza e coleta de resíduos'),
('Áreas Verdes', 'Avaliação de praças, parques e áreas verdes'),
('Saneamento', 'Avaliação de água, esgoto e drenagem'),
('Acessibilidade', 'Avaliação da acessibilidade dos espaços públicos'),
('Transporte Público', 'Avaliação da qualidade do transporte público');

CREATE OR REPLACE FUNCTION identificar_bairro(
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
)
RETURNS TABLE (
    bairro_id BIGINT,
    bairro_nome TEXT,
    regiao_id BIGINT,
    regiao_nome TEXT
)
LANGUAGE SQL
AS $$
    SELECT b.id, b.nome, r.id, r.nome
    FROM bairros b
    INNER JOIN regioes r ON r.id = b.regiao_id
    WHERE ST_Contains(
        b.area,
        ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)
    )
    LIMIT 1;
$$;

CREATE OR REPLACE VIEW indicadores_bairros AS
WITH dados AS (
    SELECT
        b.id AS bairro_id,
        b.nome AS bairro,
        r.id AS regiao_id,
        r.nome AS regiao,
        COUNT(a.id) AS quantidade_avaliacoes,
        AVG(a.nota) AS media_nota
    FROM bairros b
    INNER JOIN regioes r ON r.id = b.regiao_id
    LEFT JOIN avaliacoes a ON a.bairro_id = b.id
    GROUP BY b.id, b.nome, r.id, r.nome
),
media_geral AS (
    SELECT AVG(nota) AS media_cidade FROM avaliacoes
),
ajuste AS (
    SELECT d.*, m.media_cidade, 20 AS minimo_avaliacoes
    FROM dados d CROSS JOIN media_geral m
)
SELECT
    bairro_id,
    bairro,
    regiao_id,
    regiao,
    quantidade_avaliacoes,
    ROUND(media_nota::NUMERIC, 2) AS media_nota,
    ROUND(
        (
            (COALESCE(media_nota, media_cidade) * quantidade_avaliacoes)
            + (media_cidade * minimo_avaliacoes)
        )
        / NULLIF(quantidade_avaliacoes + minimo_avaliacoes, 0)::NUMERIC,
        2
    ) AS media_ajustada,
    ROUND(
        (
            10 -
            (
                (
                    (COALESCE(media_nota, media_cidade) * quantidade_avaliacoes)
                    + (media_cidade * minimo_avaliacoes)
                )
                / NULLIF(quantidade_avaliacoes + minimo_avaliacoes, 0)
            )
        )::NUMERIC,
        2
    ) AS indice_criticidade
FROM ajuste;

ALTER TABLE regioes ENABLE ROW LEVEL SECURITY;
ALTER TABLE bairros ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE avaliacoes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura de regioes"
ON regioes FOR SELECT TO anon USING (true);

CREATE POLICY "Permitir leitura de bairros"
ON bairros FOR SELECT TO anon USING (true);

CREATE POLICY "Permitir leitura de categorias"
ON categorias FOR SELECT TO anon USING (true);

CREATE POLICY "Permitir leitura de avaliacoes"
ON avaliacoes FOR SELECT TO anon USING (true);

CREATE POLICY "Permitir envio de avaliacoes"
ON avaliacoes FOR INSERT TO anon WITH CHECK (true);
-- Mídias anexadas às avaliações
CREATE TABLE IF NOT EXISTS avaliacao_midias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    avaliacao_id BIGINT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('foto', 'video')),
    url TEXT NOT NULL,
    caminho TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT fk_midia_avaliacao
        FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_avaliacao_midias_avaliacao
    ON avaliacao_midias(avaliacao_id);

ALTER TABLE avaliacao_midias ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir leitura de midias"
ON avaliacao_midias FOR SELECT TO anon USING (true);

CREATE POLICY "Permitir envio de midias"
ON avaliacao_midias FOR INSERT TO anon WITH CHECK (true);
